name: Markdown to PDF

on:
  push:
    branches:
      - master   # Trigger on push to main branch
  pull_request:
    branches:
      - main   # Trigger on pull request to main branch

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies (Pandoc, TeXLive)
    - name: Install pandoc and texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive

    - name: Create temporary directory
      run: mkdir -p /tmp/pandoc

    - name: Find Markdown files
      id: find_files
      run: |
        FILES=$(find ./ruokaisat -name "*.md" | sort)
        echo "$FILES"
        FILES_SINGLE_LINE=$(echo "$FILES" | tr '\n' ' ')
        echo "files=$FILES_SINGLE_LINE" >> $GITHUB_ENV

    - name: Concatenate markdown files
      run: |
        cat $FILES >> /tmp/pandoc/combined.md
        cat /tmp/pandoc/combined.md

    - name: Convert markdown to PDF
      run: pandoc /tmp/pandoc/combined.md -o /tmp/pandoc/output.pdf --verbose

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: markdown-to-pdf
        path: /tmp/pandoc/output.pdf
