name: Markdown to PDF

on:
  push:
    branches:
      - master   # Trigger on push to main branch
  pull_request:
    branches:
      - main   # Trigger on pull request to main branch

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies (Pandoc, TeXLive)
    - name: Install pandoc and texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive

    - name: Lint markdown files
      run: |
        npm install -g markdownlint-cli
        markdownlint "**/*.md"

    # Step 3: Find all markdown files in specified folders
    - name: Find Markdown files
      id: find_files
      run: |
        # Change directory to the folder containing the markdown files
        # If you have multiple folders, modify this command
        FILES=$(find ./ruokaisat -name "*.md" | sort)
        echo "$FILES"
        echo "files=$FILES" >> $GITHUB_ENV

    # Step 4: Concatenate all markdown files
    - name: Concatenate markdown files
      run: |
        cat $FILES > combined.md

    # Step 5: Convert the concatenated markdown to PDF
    - name: Convert markdown to PDF
      run: |
        pandoc combined.md -o output.pdf

    # Step 6: Upload the PDF as an artifact
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: markdown-to-pdf
        path: output.pdf
